### PR TITLE
physics informed kan

### PR DESCRIPTION
**Pull request by chaous**
I worked a lot of with PINNs (Physics-informed neural networks) and decided do the same with KANs. I trained KAN only on NS equation and boundary constrains (without data from CFD solver). My results were not perfect but steal they looked not so bad for first try with Physics-informed KAN

### CODE REVIEW

**Comment by KindXiaoming** [comment]
thank you for the great work!

**Comment by KindXiaoming** [comment]
Hi, please check that equation is correct. In the definition of `navier_stokes_residuals`, in 'x_momentum' and `y_momentum`, it should be `u_x` and `u_y` instead of `u_xx` and `u_yy`?

**Comment by KindXiaoming** [comment]
Also, grid_update (and even possibly grid extension) may be needed to make the results better.
Grid update for PDE: https://kindxiaoming.github.io/pykan/Examples/Example_6_PDE.html
Grid extension: https://kindxiaoming.github.io/pykan/Examples/Example_1_function_fitting.html

**Comment by chaous** [comment]
ok, thanks I will check everything

**Comment by chaous** [comment]
output
I fixed NS and got way better solution. Will train KAN for longer and update code

**Comment by KindXiaoming** [comment]
Thank you so much!

**Comment by chaous** [comment]
did new PR

**Pull request merged**
